title: la pescheRia
tagline: about pesco and other R packages
owner: Giovanni Bonafe'
link: https://github.com/jobonaf
copyright: Copyright Giovanni Bonafe' 2015

highlighter: pygments
pygments: true
permalink: '/:title'
markdown: rmarkdown

exclude: [README.md,"*.R","*.Rmd",figure,tmp]

